### ISSUE TITLE
giant polybars with weird output

### ISSUE THREAD

**Issue by umermasood** [Yucklys/polybar-nord-theme#15]
i followed the installation instructions but don't know what went wrong, I have this weird output:
![image](https://user-images.githubusercontent.com/70061645/179013222-0178ab0a-db1b-494d-9888-87cde1ce4f7f.png)

I am using i3-wm on debian linux.

**Comment by Yucklys** [comment]
You can customize the modules enabled for your panel by editing the `nord-config` file. By defult the project is configured to run under bspwm and Chinese language environment, so some of the module should be replaced or changed by your needs.

For the workspace indicater  for i3, use i3 instead of bspwm module.
For the error message on top panel, you can refer to the description about the clipmenu module in the README to install the prerequests.
For the error on the bottom panel, you can disable daily-poem module since it only support Chinese poem. Also you can change the default font so that the font size will be more appropriate.
