### ISSUE TITLE
error: module/mpd: Connection refused

### ISSUE THREAD

**Issue by saltbr1nger** [Yucklys/polybar-nord-theme#17]
Getting some errors when I run `./launch.sh dark` 

error: Failed to restack bar window (x1)
error: tray: Failed to put tray above 0x0a00001 in the stack (XCB_MATCH (8)) (x1)
error: module/mpd: Connection refused (x infinity)

Not sure what I did wrong.

**Comment by Yucklys** [comment]
Mpd module needs to connect to mpd port in order to grab information. Check the `mpd-port` and `mpd-host` variable in nord-config file, and change it to your mpd port. If you don't need this module, you can remove it from module list in nord-config.

For the first two errors, check for your wm on Polybar's official wiki. Generally i3 doesn't need restack and bspwm need it. Feel free to try different setting in nord-config. As long as the bar does not overlap with fullscreen applications, it should be fine.

**Comment by Yucklys** [comment]
Closing the issue. Welcome to reopen it if the issue still exist.
